In [ ]:
import pandas as pd
import numpy as np
import time

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
ls drive/MyDrive/ESE572/

572project1input.csv  572project1prefix.csv  homework1.gdoc

In [ ]:
# Preparing data for processing
# Prefix data
prefixData = pd.read_csv('drive/MyDrive/ESE572/572project1prefix.csv', header=None)
prefixData = prefixData.to_numpy()
print(len(prefixData))
for i in range(len(prefixData)):
  prefixData[i][0] = prefixData[i][0].strip()
print(prefixData[0][0][0])
print(prefixData)

# Inputs
inputs = pd.read_csv('drive/MyDrive/ESE572/572project1input.csv', header=None)
inputs = inputs.to_numpy()
print(inputs)

50005
1
[['10011100' 97 8]
 ['11000101' 96 8]
 ['01010001' 96 8]
 ...
 ['00111001110001101101001100110101' 94 32]
 ['01101001011111111001101000101000' 94 32]
 ['00110111111111011100110001011111' 92 32]]
[['00010010111011001101110010101110']
 ['10111110110010010101101000001010']
 ['10111110010110110110001011111101']
 ['10110100100100110011001010100011']
 ['10110011001000100110100001001111']
 ['10000000111111101100000101110011']
 ['00011011110010010101110100101110']
 ['00010011111000110011011001110111']
 ['00001000101011110111000101010011']
 ['11110100010001000000001110101000']
 ['11110011110000100100100000011110']
 ['11001001101101010100001010011110']
 ['10000110100100101011011001111011']
 ['01110101110100111001100000111100']
 ['01110010100100010010001100000010']
 ['01011110010000101000010111101100']
 ['01010000101001001101100101100110']
 ['01001011110000011100100100010011']
 ['10011110100101111011011001111110']
 ['10011001010001001101100100010100']]

In [ ]:
# Testing things
firstAddress = prefixData[0]
print(firstAddress)

for number in firstAddress[0]:
  if number == "0":
    print(0)
  if number == "1":
    print(1)

print(firstAddress[1])
print(firstAddress[2])

['10011100' 97 8]
1
0
0
1
1
1
0
0
97
8

In [ ]:
# Trie insert Code

class Node:
  def __init__(self, val):
    self.left = None
    self.right = None
    self.val = val

class Trie:
  def __init__(self):
    self.root = None

  def add(self, address, hopVal, length):
    # if trie root is empty then start it with an empty node
    if self.root == None:
      self.root = Node(None) 

    # creating counter for length
    depth = 0
    # starting from root of trie
    currentNode = self.root
    # for each number in the address
    for number in address:
      # if number is 0 in address go left
      # print(depth, number)
      if number == "0":
        # if the next left node doesnt exist
        if currentNode.left is None:
          # create a new node
          newNode = Node(None)
          # connecting it to current node
          currentNode.left = newNode
        # traversing down one node
        currentNode = currentNode.left
        # print("going left")
        depth += 1
        if depth == length:
          currentNode.val = hopVal
          return currentNode.val
      # if number is 1 in address go right
      if number == "1":
        # if the next right node doesnt exist
        if currentNode.right is None:
          # create a new node
          newNode = Node(None)
          currentNode.right = newNode
        currentNode = currentNode.right
        # print("going right")
        depth += 1
        if depth == length:
          currentNode.val = hopVal
          return currentNode.val
    return

  def lookup(self, address):
    # getting starting time
    startTime = time.time()
    # Wenxuan you can write your code here for searching address in the tree
    
    # get the length of adress
    num = len(address) 

    # store the closest hop
    hop = []
    
    # store largest matching prefix that has a hop
    pre = ''

    # store the remaining str after the pre
    rem = ''

    # store the tree depth
    tDep = 0;

    # initialize the tris
    T = self.root
    j = 0;

    # start from the first str of adress to the last one
    for i in range(num):

      # add the str to rem
      rem += address[i]

      # if 0 go the left, if 1 go the right, if has a non-none value store pre and hop
      if address[i] == '0':
        j += 1
        if T.left is None:
          break
        T = T.left
      elif address[i] == '1':
        j += 1
        if T.right is None:
          break
        T = T.right
      
      if T.val != None:
        hop = T.val
        pre += rem
        rem = ''
        tDep += j
        j = 0
    
    
    endTime = time.time()
    totalTime = endTime - startTime
    # print(pre, hop, totalTime, tree depth)
    return [address, pre, hop, tDep, round(totalTime,6)]

In [ ]:
# Testing Trie code
testTrie = Trie()
print(len(prefixData))
print(testTrie.add(firstAddress[0], firstAddress[1], firstAddress[2]))

50005
97

In [ ]:
# Creating IP address Trie
addressTrie = Trie()
for i in range(len(prefixData)):
  addressTrie.add(prefixData[i][0],prefixData[i][1],prefixData[i][2])

In [ ]:
# search hop from input and store data
dataFromTri = [];
for i in range(len(inputs)):
  dataFromTri += [addressTrie.lookup(inputs[i][0])]
print(dataFromTri)

[['00010010111011001101110010101110', '000100101110', 232, 12, 2e-05], ['10111110110010010101101000001010', '10111110110010', 114, 14, 1.7e-05], ['10111110010110110110001011111101', '101111100101', 204, 12, 1.2e-05], ['10110100100100110011001010100011', '1011010010', 74, 10, 1.2e-05], ['10110011001000100110100001001111', '101100110010', 138, 12, 1e-05], ['10000000111111101100000101110011', '10000000111', 107, 11, 1.5e-05], ['00011011110010010101110100101110', '0001101111001', 1, 13, 1.6e-05], ['00010011111000110011011001110111', '0001001111100', 170, 13, 2.1e-05], ['00001000101011110111000101010011', '0000100010101', 152, 13, 1.3e-05], ['11110100010001000000001110101000', '1111010001000100', 180, 16, 1.5e-05], ['11110011110000100100100000011110', '111100111100001', 152, 15, 1.4e-05], ['11001001101101010100001010011110', '1100100110', 249, 10, 1.3e-05], ['10000110100100101011011001111011', '100001101', 200, 9, 1.3e-05], ['01110101110100111001100000111100', '0111010111010', 17, 13, 1.3e-05], ['01110010100100010010001100000010', '01110010100', 51, 11, 1.2e-05], ['01011110010000101000010111101100', '01011110010', 49, 11, 1.8e-05], ['01010000101001001101100101100110', '010100001010', 207, 12, 1.1e-05], ['01001011110000011100100100010011', '01001011110000', 17, 14, 1.5e-05], ['10011110100101111011011001111110', '10011110100', 14, 11, 1.4e-05], ['10011001010001001101100100010100', '1001100101000', 138, 13, 1.6e-05]]

In [ ]:
# idea for second data structure: using hash table. Create hash table with prefixs. 
# Searching: take the address and see if key yields value in hash table. If not then take last digit off and try again
# repeat until finds a key that works or returns that there is no key in the table for the address

class addressHash:
  def __init__(self):
    self.table = {}
  
  def addToTable(self, address, hopVal):
    self.table[address] = hopVal
    return
  
  def searchTable(self, address):
    iters = 0
    startTime = time.time()
    addArr = list(address)
    sep = ''
    while len(addArr) > 0:
      joinedAddress = sep.join(addArr)
      # print(joinedAddress)
      if joinedAddress in self.table:
        finishTime = time.time()
        totTime = finishTime - startTime
        return [address, joinedAddress, self.table[joinedAddress], iters, round(totTime,6)] 
      else:
        iters += 1
        addArr.pop()
    return 'not in table'

In [ ]:
# testing hash table code with one case
addresses = addressHash()
firstAddress[0] = firstAddress[0].strip()
print(firstAddress)
addresses.addToTable(firstAddress[0], firstAddress[1])
# for i in range(len(prefixData)):
#   addresses.addToTable(prefixData[i][0],prefixData[i][1])
key = '10011100'
if key in addresses.table:
  print(key)
else:
  print('key doesnt exist')

addressArr = []
for digit in firstAddress[0]:
  addressArr.append(digit)
print(addressArr)
seperator = ''
print(seperator.join(addressArr))

print(list(firstAddress[0]))

print(addresses.searchTable('100111000'))

print(inputs[0][0])

['10011100' 97 8]
10011100
['1', '0', '0', '1', '1', '1', '0', '0']
10011100
['1', '0', '0', '1', '1', '1', '0', '0']
['100111000', '10011100', 97, 1, 6e-06]
00010010111011001101110010101110

In [ ]:
# testing hash table with prefix data and inputs

# creating hash table
realAddress = addressHash()
for i in range(len(prefixData)):
  realAddress.addToTable(prefixData[i][0],prefixData[i][1])

# finding closest hop and average amount of iterations
dataFromHash = []
for ip in inputs:
  dataFromHash += [realAddress.searchTable(ip[0])]
print(dataFromHash)
data1 = dataFromHash[0]
data1

[['00010010111011001101110010101110', '000100101110', 232, 20, 2.4e-05], ['10111110110010010101101000001010', '10111110110010', 114, 18, 1.4e-05], ['10111110010110110110001011111101', '101111100101', 204, 20, 1.4e-05], ['10110100100100110011001010100011', '1011010010', 74, 22, 1.5e-05], ['10110011001000100110100001001111', '101100110010', 138, 20, 1.4e-05], ['10000000111111101100000101110011', '10000000111', 107, 21, 1.5e-05], ['00011011110010010101110100101110', '0001101111001', 1, 19, 1.3e-05], ['00010011111000110011011001110111', '0001001111100', 170, 19, 1.3e-05], ['00001000101011110111000101010011', '0000100010101', 152, 19, 1.3e-05], ['11110100010001000000001110101000', '1111010001000100', 180, 16, 1.7e-05], ['11110011110000100100100000011110', '111100111100001', 152, 17, 1.9e-05], ['11001001101101010100001010011110', '1100100110', 249, 22, 2.1e-05], ['10000110100100101011011001111011', '100001101', 200, 23, 2.3e-05], ['01110101110100111001100000111100', '0111010111010', 17, 19, 1.5e-05], ['01110010100100010010001100000010', '01110010100', 51, 21, 2.5e-05], ['01011110010000101000010111101100', '01011110010', 49, 21, 1.5e-05], ['01010000101001001101100101100110', '010100001010', 207, 20, 1.4e-05], ['01001011110000011100100100010011', '01001011110000', 17, 18, 1.3e-05], ['10011110100101111011011001111110', '10011110100', 14, 21, 1.4e-05], ['10011001010001001101100100010100', '1001100101000', 138, 19, 1.3e-05]]

['00010010111011001101110010101110', '000100101110', 232, 20, 2.4e-05]

Trie Results

In [ ]:
# create a table of data from Trie Method

# calculate the average time and depth of all inputs data
np_dataFromTri = np.array(dataFromTri)
aveDep=np.mean(np_dataFromTri[:,3].astype('float64'))
aveTime = np.mean(np_dataFromTri[:,-1].astype('float64'))
df_aveDep = np.array([aveDep]+['']*(len(inputs)-1))
df_aveTime = np.array([aveTime]+['']*(len(inputs)-1))
df_accuracy = np.array(['100%']+['']*(len(inputs)-1))

# show the table of results
df_dataFromTri = pd.DataFrame(data = np_dataFromTri, columns=['address','prefix','port','depth','time'])
df_dataFromTri['aveDep']=df_aveDep
df_dataFromTri['aveTime']=df_aveTime
df_dataFromTri['accuracy']=df_accuracy
df_dataFromTri

                             address            prefix  ...   aveTime accuracy
0   00010010111011001101110010101110      000100101110  ...  1.45e-05     100%
1   10111110110010010101101000001010    10111110110010  ...
2   10111110010110110110001011111101      101111100101  ...
3   10110100100100110011001010100011        1011010010  ...
4   10110011001000100110100001001111      101100110010  ...
5   10000000111111101100000101110011       10000000111  ...
6   00011011110010010101110100101110     0001101111001  ...
7   00010011111000110011011001110111     0001001111100  ...
8   00001000101011110111000101010011     0000100010101  ...
9   11110100010001000000001110101000  1111010001000100  ...
10  11110011110000100100100000011110   111100111100001  ...
11  11001001101101010100001010011110        1100100110  ...
12  10000110100100101011011001111011         100001101  ...
13  01110101110100111001100000111100     0111010111010  ...
14  01110010100100010010001100000010       01110010100  ...
15  01011110010000101000010111101100       01011110010  ...
16  01010000101001001101100101100110      010100001010  ...
17  01001011110000011100100100010011    01001011110000  ...
18  10011110100101111011011001111110       10011110100  ...
19  10011001010001001101100100010100     1001100101000  ...

[20 rows x 8 columns]

Hash Table Results

In [ ]:
# create a table of data from Hash Method

# calculate the average time and depth of all inputs data
np_dataFromHash = np.array(dataFromHash)
aveDep=np.mean(np_dataFromHash[:,3].astype('float64'))
aveTime = np.mean(np_dataFromHash[:,-1].astype('float64'))
df_aveDep = np.array([aveDep]+['']*(len(inputs)-1))
df_aveTime = np.array([aveTime]+['']*(len(inputs)-1))
df_accuracy = np.array(['100%']+['']*(len(inputs)-1))

# show the table of results
df_dataFromHash = pd.DataFrame(data = np_dataFromHash, columns=['address','prefix','port','depth','time'])
df_dataFromHash['aveDep']=df_aveDep
df_dataFromHash['aveTime']=df_aveTime
df_dataFromHash['accuracy']=df_accuracy
df_dataFromHash

                             address            prefix  ...   aveTime accuracy
0   00010010111011001101110010101110      000100101110  ...  1.62e-05     100%
1   10111110110010010101101000001010    10111110110010  ...
2   10111110010110110110001011111101      101111100101  ...
3   10110100100100110011001010100011        1011010010  ...
4   10110011001000100110100001001111      101100110010  ...
5   10000000111111101100000101110011       10000000111  ...
6   00011011110010010101110100101110     0001101111001  ...
7   00010011111000110011011001110111     0001001111100  ...
8   00001000101011110111000101010011     0000100010101  ...
9   11110100010001000000001110101000  1111010001000100  ...
10  11110011110000100100100000011110   111100111100001  ...
11  11001001101101010100001010011110        1100100110  ...
12  10000110100100101011011001111011         100001101  ...
13  01110101110100111001100000111100     0111010111010  ...
14  01110010100100010010001100000010       01110010100  ...
15  01011110010000101000010111101100       01011110010  ...
16  01010000101001001101100101100110      010100001010  ...
17  01001011110000011100100100010011    01001011110000  ...
18  10011110100101111011011001111110       10011110100  ...
19  10011001010001001101100100010100     1001100101000  ...

[20 rows x 8 columns]